### ISSUE TITLE
Unformatted TimeCondition description

### ISSUE THREAD

**Issue by NEckes** [SengGruppe/QuickNotes#2]
![unbenannt](https://user-images.githubusercontent.com/5845106/42133456-ae4936d6-7d2a-11e8-9c6d-03badcd068c2.PNG)
This doesn't look fancy...

**Comment by Bonebreaker9** [comment]
![grafik](https://user-images.githubusercontent.com/11709937/42210018-702b0294-7eb0-11e8-824d-597139c30600.png)
So in Ordnung?
